---

# Runtime
verbose: 3
token: lstbknd

# Etcd database
etcd:
  prefix: lastbackend
  endpoints:
    "127.0.0.1:2379"

# Domain
domain:
  internal: "lb.local"
  external: "lstbknd.io"

api:
  host: 0.0.0.0
  port: 2967
  uri: "api.lstbknd.net"
  tls:
    insecure: false
    ca: "/opt/cert/lastbackend/ca.pem"
    cert: "/opt/cert/lastbackend/server.pem"
    key: "/opt/cert/lastbackend/server-key.pem"

dns:
  host: 0.0.0.0
  port: 53
  default_ip: "127.0.0.1"