---

# Runtime
verbose: 3
token: cluster-token
ssl: true

# Etcd database
etcd:
  prefix: lastbackend
  endpoints:
    "127.0.0.1:2379"

# Domain
domain:
  internal: "lb.local"
  external: "lstbknd.io"

api:
  host: 0.0.0.0
  port: 2967
  uri: "api.lstbknd.net"
  tls: false

# Discovery settings
discovery:
  host: 0.0.0.0
  port: 5380
  default_ips:
    - "127.0.0.1"

  cache:
    duration: 1440  # minutes
    enabled: true