---

# Runtime
verbose: 3
token: lstbknd
ssl: true

# Etcd database
etcd:
  prefix: lastbackend
  endpoints:
    "127.0.0.1:2379"

# Domain
domain:
  internal: "lb.local"
  external: "lstbknd.io"

api:
  host: 0.0.0.0
  port: 2967
  uri: "api.lstbknd.net"
  tls: false

dns:
  host: 0.0.0.0
  port: 53
  default_ip: "127.0.0.1"