sudo: required
language: go

services:
  - docker

go:
  - 1.9

install:
  - make deps

script:
  - make build

after_success:
  - make docs

notifications:
  slack: lastbackend:0e7apir97phOrZbD12RJ9v0P

deploy:
  - provider: pages
    local_dir: docs/output
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
